config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for 	:users,
  				path: "",
  				path_names: { sign_in: "login", sign_out: "logout", edit: "profile" },
  				controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }


  resources :users, only: [:show]
  
  resources :photos

  resources :rooms, except: [:destroy] do
  	resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end

  resources :reservations, only: [:create] do
    resource :feedback, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  
  get "/preload" => "reservations#preload"
  get "/preview" => "reservations#preview"
  get "/your_trips" => "reservations#your_trips"
  get "/your_reservations" => "reservations#your_reservations"
  get "/search" => "pages#search"


end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  #attributes for comments, user_id, reservation_id, guest_id

  belongs_to :user
  belongs_to :reservation


end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	before_action :authenticate_user!

	def create
		guest = User.find(params[:feedback][:guest_id])
		
		if !guest.feedback_exists?(current_user)
			feedback = current_user.feedbacks.create!(feedback_params)	
		end
		
		redirect_to user_path(guest.id)
	end

	private
		def feedback_params
			params.require(:feedback).permit(:comment, :reservation_id, :guest_id)
		end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for [@reservation, @feedback], url: reservation_feedback_path(@reservation) do |f| %>
	<div class="form-group">
		<%= f.text_area :comment, rows: 3, class: "form-control" %>
	</div>
		<%= f.hidden_field :reservation_id, value: @reservation.id %>
		<%= f.hidden_field :guest_id, value: @user.id %>
	<div class="actions">
		<%= f.submit "Create", class: "btn btn-primary" %>
	</div>

<% end %>