config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for 	:users,
  				path: "",
  				path_names: { sign_in: "login", sign_out: "logout", edit: "profile" },
  				controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }


  resources :users, only: [:show]
  
  resources :photos

  resources :rooms, except: [:destroy] do
  	resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end

  resources :reservations, only: [:create] do
    resource :feedback, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  
  get "/preload" => "reservations#preload"
  get "/preview" => "reservations#preview"
  get "/your_trips" => "reservations#your_trips"
  get "/your_reservations" => "reservations#your_reservations"
  get "/search" => "pages#search"


end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # validates :photos, presence: true
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bedroom, presence: true
  validates :bathroom, presence: true
  validates :listing_name, presence: true, length: { maximum: 50 }
  validates :summary, presence: true, length: { maximum: 50 }
  validates :address, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def show_first_photo(size)
    if self.photos.length == 0
      "http://placehold.it/120x66"
    else
      self.photos[0].image.url(size)
    end
  end

  def average_rating
    if reviews.count == 0
      return 0
    else
      reviews.average(:star).round(2)
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos

    @booked = Reservation.where("room_id = ? AND user_id = ?", @room.id, current_user.id).present? if current_user
    @reviews = @room.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @room = current_user.rooms.new
  end

  def create
    @room = current_user.rooms.new(room_params)
    if @room.save
      if params[:images]
        params[:images].each do |image|
          @room.photos.create!(image: image)
        end
      end

      @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Room created!"
    else
      flash[:alert] = "Room could not be created!"
      render :new
    end
  end

  def edit
    if current_user.id == @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, notice: "You cannot do this!"
    end
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      
      # @photos = @room.photos // testing to see if I don't need this?
      redirect_to edit_room_path(@room), notice: "Room updated!!"
    else
      flash[:alert] = "Room could not be updated!"
      render :edit
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accomodate, :bedroom, :bathroom, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_ac, :is_heating, :is_internet, :price, :active)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Add your beautiful place
	</div>
	<div class="panel-body">
		<div class="container">
			
			<%= form_for @room, html: { multipart: true } do |f| %>
				<div class="row">
					<div class="col-md-4 select">
						<div class="form-group">
							<label for="">Home Type</label>
							<%= f.select :home_type, options_for_select([["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]]), id: "home_type", prompt: "Select", class: "form-control" %>
						</div>
					</div>
					<div class="col-md-4 select">
						<div class="form-group">
							<label for="">Room Type</label>
							<%= f.select :room_type, [["Entire Home", "Entire Home"], ["Private", "Private"], ["Shared", "Shared"]], prompt: "Select", class: "form-control" %>
						</div>
					</div>
					<div class="col-md-4 select">
						<div class="form-group">
							<label for="">Accomodate</label>
							<%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6+", 6]], prompt: "Select", class: "form-control" %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Bedrooms</label>
							<%= f.select :bedroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select", class: "form-control" %>
						</div>
					</div>
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Bathrooms</label>
							<%= f.select :bathroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select", class: "form-control" %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="form-group">
						<label>Listing Name</label>
						<%= f.text_field :listing_name, placeholder: "Anything you want!", class: "form-control" %>
					</div>
					<div class="form-group">
						<label>Summary</label>
						<%= f.text_area :summary, placeholder: "Tell us about your home", class: "form-control" %>
					</div>
					<div class="form-group">
						<label>Address</label>
						<%= f.text_field :address, placeholder: "What is your address?", class: "form-control" %>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<%= f.check_box :is_tv %> TV
						</div>
						<div class="form-group">
							<%= f.check_box :is_kitchen %> Kitchen
						</div>
						<div class="form-group">
							<%= f.check_box :is_internet %> Internet
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<%= f.check_box :is_heating %> Heating
						</div>
						<div class="form-group">
							<%= f.check_box :is_ac %> Air Conditioning
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<label>Nightly Price</label>
							<div class="input-group">
								<div class="input-group-addon">$</div>
								<%= f.text_field :price, placeholder: "eg. $100", class: "form-control" %>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<span class="btn btn-default btn-file">
								<i class="fa fa-cloud-upload fa-large"></i> Upload Photos
								<%= file_field_tag "images[]", type: :file, multiple: true %>
							</span>
						</div>
					</div>
				</div>

				<div id="photos"><%= render "photos/list" %></div>

				<div class="row">
					<div class="form-group">
						<%= f.check_box :active %> Active?
					</div>
				</div>

				<div class="actions">
					<%= f.submit "Save", class: "btn btn-primary" %>
				</div>

			<% end %>
		</div>
	</div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render "form" %>

app/views/rooms/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Reservations", your_reservations_path, class: "sidebar-link" %></li>
			<li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">
				<% @rooms.each do |room| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag room.show_first_photo(:thumb) %>
						</div>
						<div class="col-md-7">
							<h4><%= room.listing_name %></h4>
						</div>
						<div class="col-md-3 right">
							<%= link_to "Update", edit_room_path(room), class: "btn btn-primary" %>
						</div>
					</div>
					<hr>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/rooms/new.html.erb
<%= render "form" %>

app/views/rooms/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<!-- Image -->
		<div class="row">
			<div class="col-md-12">
				<%= image_tag @photos[0].image.url, class: "img-responsive" if @photos.length > 0 %>
			</div>
		</div>

		<br>

		<!-- Main Info -->
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-3 text-center">
						<%= image_tag avatar_url(@room.user), class: "img-circle avatar-large" %><br><br>
						<%= @room.user.fullname %>
					</div>
					<div class="col-md-9">
						<h4><%= @room.listing_name %></h4>
						<%= @room.address %>
						<div class="row text-center row-space-1">
							<div class="col-sm-3">
								<i class="fa fa-home fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-users fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-bed fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-ship fa-2x"></i>
							</div>
						</div>

						<div class="row text-center">
							<div class="col-sm-3">
								<%= @room.home_type %>
							</div>
							<div class="col-sm-3">
								<%= pluralize @room.accomodate, "Guest" %>
							</div>
							<div class="col-sm-3">
								<%= pluralize @room.bedroom, "Bedroom" %>
							</div>
							<div class="col-sm-3">
								<%= pluralize @room.bathroom, "Bathroom" %>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<!-- Reservation form -->
				<% if !current_user.rooms.include?(@room) %>
					<%= render "reservations/form" %>
				<% end %>
			</div>
		</div>

		<!-- About -->
		<div class="row">
			<div class="col-md-12">
				<h2>About This Listing</h2>
				<p><%= @room.summary %></p>
			</div>
		</div>

		<!-- Amenities -->
		<div class="row">
			<div class="col-md-2">
				<p>Amenities</p>
			</div>
			<div class="col-md-10">
				<div class="row">
					<div class="col-md-6">
						<ul class="amenities">
							<li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
							<li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
							<li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="amenities">
							<li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
							<li class="<%= 'text-line-through' if !@room.is_ac %>">Air Conditioning</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<!-- Carousel -->
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">
				  <!-- Indicators -->
				  <% if @photos %>
					  <ol class="carousel-indicators">
					    <% @photos.each do |photo| %>
					    	<li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
				    	<% end %>
					  </ol>
				  <% end %>

				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
				    <% if @photos %>
						<% @photos.each do |photo| %>
						    <div class="item <%= 'active' if photo.id == @photos[0].id %>">
						      <%= image_tag photo.image.url %>
						    </div>
					    <% end %>
					<% end %>
				  </div>

				  <!-- Left and right controls -->
				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>
			</div>
		</div>
		
		<br>
		<hr>

		<!-- Reviews -->
		<div class="row">
			<div class="col-md-12">
				<h3>Reviews <span id="average_rating"></span> (<%= @reviews.count %>)</h3>
				<div class="container">
					<div>
						<%= render "reviews/form" if @booked && !@hasReview %>
					</div>
					<div>
						<%= render "reviews/list" %>
					</div>
				</div>
			</div>
		</div>

		<!-- Google Maps -->
		<div class="row">
			<div class="col-md-12">
				<div id="map"></div>
				<style>
				  #map {
				    width: 100%;
				    height: 400px;
				    background-color: #CCC;
				  }
				</style>

				<script>
			      function initMap() {
			        var mapDiv = document.getElementById('map');
			        var map = new google.maps.Map(mapDiv, {
			          center: {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>},
			          zoom: 14
			        });
			        var marker = new google.maps.Marker({
			        	position: {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>},
			        	map: map,
			        	title: "Hello World"
			        });
			        marker.setMap(map);
			      }
			    </script>
			    <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
			        async defer></script>
			</div>
		</div>

		<!-- Nearby Rooms -->
		<div class="row">
			<h2>Nearby Rooms</h2>
			<% for room in @room.nearbys(10) %>
				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading preview">
							<%= image_tag room.show_first_photo(:medium) %>
						</div>
						<div class="panel-body">
							<%= link_to room.listing_name, room_path(room) %><br>
							(<%= pluralize room.distance.round(2), "mile" %> away)
						</div>
					</div>
				</div>
			<% end %>
		</div>






	</div>
</div>

<script>
			$("#average_rating").raty({
				path: "/assets",
				readOnly: true,
				score: <%= @room.average_rating %>
			});
		</script>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>